name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - boards/**
      - build.yaml
      - .github/workflows/**
  pull_request:
    paths:
      - config/**
      - boards/**
      - build.yaml
      - .github/workflows/**

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
